# Generated by Django 5.0 on 2024-04-03 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('discount', models.FloatField()),
                ('availability', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
    ]
